{
 "title": "1.1 Server Performance Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Alias",
    "query": "SHOW TAG VALUES WITH KEY = Alias"
   },
   {
    "name": "hostname",
    "query": "SHOW TAG VALUES WITH KEY = host where Alias =~ /$Alias/"
   },
   {
    "name": "Cpu",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~/$hostname/ and Alias =~ /$Alias/"
   },
   {
    "name": "Network_Ethernet",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~/$hostname/ and Alias =~ /$Alias/"
   },
   {
    "name": "FileSystem",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~/$hostname/ and Alias =~ /$Alias/"
   },
   {
    "name": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~/$hostname/ and Alias =~ /$Alias/"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "query": "SELECT \"usage_idle\" *-1+100 AS \"Total\" FROM \"autogen\".\"cpu\" WHERE (\"Alias\" =~ /^$Alias$/ AND \"host\" =~ /^$hostname$/ AND \"cpu\" = 'cpu-total') AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       { "params": [ "*-1+100" ], "type": "math" },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       { "params": [ "running" ], "type": "alias" }
      ],
      [
       { "params": [ "sleeping" ], "type": "field" },
       { "params": [ "sleeping" ], "type": "alias" }
      ],
      [
       { "params": [ "zombies" ], "type": "field" },
       { "params": [ "zombies" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Zombie",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_host",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Detail",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       { "params": [ "User" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       { "params": [ "System" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       { "params": [ "softirq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       { "params": [ "steal" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_nice" ], "type": "field" },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_irq" ], "type": "field" },
       { "params": [ "irq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       { "params": [ "iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_guest" ], "type": "field" },
       { "params": [ "quest" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_guest_nice" ], "type": "field" },
       { "params": [ "quest_nice" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       { "params": [ "total(%)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "LoadAverage Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       { "params": [ "1min" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       { "params": [ "5min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Detail Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "cached" ], "type": "field" },
       { "params": [ "Cached" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "buffered" ], "type": "field" },
       { "params": [ "Buffered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Disk Read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host : $tag_name",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "Alias" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host : $tag_name",
     "groupBy": [
      { "params": [ "Alias" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk F/S Usage(%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_path",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\"  FROM \"autogen\".\"disk\" WHERE (\"Alias\" =~ /^$Alias$/ AND \"host\" =~ /^$hostname$/ AND \"path\" =~ /^$FileSystem$/) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^$FileSystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Inode Usage(%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host : $tag_path",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT ( \"inodes_used\" / \"inodes_total\" ) * 100 FROM \"disk\" WHERE (\"Alias\" =~ /^$Alias$/ AND \"host\" =~ /^$hostname$/ AND \"path\" =~ /^$FileSystem$/ ) AND $timeFilter GROUP BY \"host\", \"path\"",
     "select": [
      [
       { "params": [ "inodes_used" ], "type": "field" },
       { "params": [ "/" ], "type": "math" }
      ],
      [
       { "params": [ "inodes_total" ], "type": "field" },
       { "params": [ "/" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Kernel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Context switches",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "kernel",
     "query": "SELECT mean(tcp_close) as CLOSED, mean(tcp_close_wait) as CLOSE_WAIT, mean(tcp_closing) as CLOSING, mean(tcp_established) as ESTABLISHED, mean(tcp_fin_wait1) as FIN_WAIT1, mean(tcp_fin_wait2) as FIN_WAIT2, mean(tcp_last_ack) as LAST_ACK, mean(tcp_syn_recv) as SYN_RECV, mean(tcp_syn_sent) as SYN_SENT, mean(tcp_time_wait) as TIME_WAIT FROM \"netstat\" WHERE (\"Alias\" =~ /^$Alias$/ AND \"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "context_switches" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "context switches" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "forks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "kernel",
     "query": "SELECT mean(tcp_close) as CLOSED, mean(tcp_close_wait) as CLOSE_WAIT, mean(tcp_closing) as CLOSING, mean(tcp_established) as ESTABLISHED, mean(tcp_fin_wait1) as FIN_WAIT1, mean(tcp_fin_wait2) as FIN_WAIT2, mean(tcp_last_ack) as LAST_ACK, mean(tcp_syn_recv) as SYN_RECV, mean(tcp_syn_sent) as SYN_SENT, mean(tcp_time_wait) as TIME_WAIT FROM \"netstat\" WHERE (\"Alias\" =~ /^$Alias$/ AND \"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "processes_forked" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "forks" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "linux_sysctl_fs",
     "query": "SELECT mean(tcp_close) as CLOSED, mean(tcp_close_wait) as CLOSE_WAIT, mean(tcp_closing) as CLOSING, mean(tcp_established) as ESTABLISHED, mean(tcp_fin_wait1) as FIN_WAIT1, mean(tcp_fin_wait2) as FIN_WAIT2, mean(tcp_last_ack) as LAST_ACK, mean(tcp_syn_recv) as SYN_RECV, mean(tcp_syn_sent) as SYN_SENT, mean(tcp_time_wait) as TIME_WAIT FROM \"netstat\" WHERE (\"Alias\" =~ /^$Alias$/ AND \"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "file-max" ], "type": "field" },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "file-nr" ], "type": "field" },
       { "params": [ "opened" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Network stack (TCP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "TX(MB/S)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host -   $tag_interface",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "bytes_sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$Network_Ethernet$/" }
     ]
    }
   ]
  },
  {
   "title": "RX(MB/S)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host -   $tag_interface",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(first(\"bytes_recv\"), 1s) AS \"bytes_recv\" FROM \"net\" WHERE (\"Alias\" =~ /^$Alias$/ AND \"host\" =~ /^$hostname$/ AND \"interface\" =~ /^$Network_Ethernet$/) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "bytes_recv" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$Network_Ethernet$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP handshake issues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(\"tcp_estabresets\", 1s) AS \"estabresets\" FROM \"autogen\".\"net\" WHERE (\"Alias\" =~ /^$Alias$/ AND \"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "tcp_estabresets" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "estabresets" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(\"tcp_outrsts\", 1s) AS \"outrsts\" FROM \"autogen\".\"net\" WHERE (\"Alias\" =~ /^$Alias$/ AND \"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "tcp_outrsts" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "outrsts" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Alias", "operator": "=~", "value": "/^$Alias$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"tcp_activeopens\", 1s) AS \"activeopens\" FROM \"autogen\".\"net\" WHERE (\"Alias\" =~ /^$Alias$/ AND \"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(\"tcp_passiveopens\", 1s) AS \"passiveopens\" FROM \"autogen\".\"net\" WHERE (\"Alias\" =~ /^$Alias$/ AND \"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}